# Documentation:
# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

plugin_directories: ['.scss-linters']

scss_files: '{ui,site/assets/styles}/**/*.scss'
exclude:
  - node_modules
  - git_modules
  - app_modules
  - ui/vendor/**
  - site/assets/styles/_vendor/**
linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
  BorderZero:
    enabled: true
  ColorKeyword:
    enabled: true
  ColorVariable:
    enabled: false
  Comment:
    enabled: true
    allowed: 'Copyright'
  DeclarationOrder:
    enabled: false
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  EmptyRule:
    enabled: true
    severity: error
  ExtendDirective:
    enabled: true
    severity: error
  FinalNewline:
    enabled: false # Already checked by another task
  HexLength:
    enabled: true
    style: short
  HexNotation:
    enabled: true
    style: lowercase
  HexValidation:
    enabled: true
  IdSelector:
    enabled: true
    severity: error
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
  ImportantRule:
    enabled: true
  Indentation:
    enabled: false # Already checked by another task
  LeadingZero:
    enabled: true
    style: include_zero
  MergeableSelector:
    enabled: true
    force_nesting: true
  NameFormat:
    enabled: true
    allow_leading_underscore: true # For private variables, mixins and functions
    convention: '^[a-z]|[a-z0-9\-]{2,}$'
    convention_explanation: 'Valid names for variables, mixins and functions: i, foo, foo-bar, foo-1, _private-thing'
    severity: error
  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: true
  PlaceholderInExtend:
    enabled: false
  PropertyCount:
    enabled: false
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: true
  PseudoElement:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: true
    max_depth: 3
  SelectorFormat:
    enabled: true
    convention: '^[a-z0-9_\-]+$'
    convention_explanation: 'Valid class names: block_container, block, block_modifier, block--modifier (deprecated), block__element, block__element--modifier (deprecated), block__element_modifier'
    severity: error
  Shorthand:
    enabled: false
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space_or_newline
  SpaceAfterVariableName:
    enabled: true
  SpaceAroundOperator:
    enabled: true
    style: one_space
  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: true
  StringQuotes:
    enabled: true
    style: single_quotes
  TrailingSemicolon:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlQuotes:
    enabled: true
  VendorPrefix:
    enabled: true
  ZeroUnit:
    enabled: true
  DisallowLastParentSelector:
    enabled: true
    severity: error
    exclude:
      - site/assets/styles/**
